config-version = 2
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
accordion-padding = 24

on-focused-monitor-changed = ["move-mouse monitor-lazy-center"]

[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 8
outer.bottom = 8
outer.top = 8
outer.right = 8

[mode.main.binding]
ctrl-alt-shift-cmd-enter = "exec-and-forget open -na WezTerm"
ctrl-alt-shift-cmd-r = "reload-config"

ctrl-alt-shift-cmd-slash = "layout tiles horizontal vertical"
ctrl-alt-shift-cmd-comma = "layout accordion horizontal vertical"
ctrl-alt-shift-cmd-v = "join-with down"
ctrl-alt-shift-cmd-b = "join-with right"
ctrl-alt-shift-cmd-f = "layout floating tiling"

ctrl-alt-shift-cmd-h = "focus left"
ctrl-alt-shift-cmd-j = "focus down"
ctrl-alt-shift-cmd-k = "focus up"
ctrl-alt-shift-cmd-l = "focus right"

ctrl-alt-shift-cmd-u = "move left"
ctrl-alt-shift-cmd-i = "move down"
ctrl-alt-shift-cmd-o = "move up"
ctrl-alt-shift-cmd-p = "move right"

ctrl-alt-shift-cmd-minus = "resize smart -50"
ctrl-alt-shift-cmd-equal = "resize smart +50"

ctrl-alt-shift-cmd-1 = "workspace 1"
ctrl-alt-shift-cmd-2 = "workspace 2"
ctrl-alt-shift-cmd-3 = "workspace 3"
ctrl-alt-shift-cmd-4 = "workspace 4"
ctrl-alt-shift-cmd-5 = "workspace 5"
ctrl-alt-shift-cmd-6 = "workspace 6"
ctrl-alt-shift-cmd-7 = "workspace 7"
ctrl-alt-shift-cmd-8 = "workspace 8"
ctrl-alt-shift-cmd-9 = "workspace 9"

ctrl-alt-shift-cmd-leftSquareBracket = "fullscreen on --no-outer-gaps"
ctrl-alt-shift-cmd-rightSquareBracket = "fullscreen off"

ctrl-alt-shift-cmd-m = "mode send"

[mode.send.binding]
esc = "mode main"
1 = ["move-node-to-workspace 1", "mode main"]
2 = ["move-node-to-workspace 2", "mode main"]
3 = ["move-node-to-workspace 3", "mode main"]
4 = ["move-node-to-workspace 4", "mode main"]
5 = ["move-node-to-workspace 5", "mode main"]
6 = ["move-node-to-workspace 6", "mode main"]
7 = ["move-node-to-workspace 7", "mode main"]
8 = ["move-node-to-workspace 8", "mode main"]
9 = ["move-node-to-workspace 9", "mode main"]

[[on-window-detected]]
if.app-id = "ru.keepcoder.Telegram"
run = "move-node-to-workspace 5"

[[on-window-detected]]
if.app-id = "com.spotify.client"
run = "move-node-to-workspace 6"

[[on-window-detected]]
if.app-id = "ch.protonmail.desktop"
run = "move-node-to-workspace 7"

[[on-window-detected]]
if.app-id = "com.openai.codex"
run = "move-node-to-workspace 4"

[[on-window-detected]]
if.app-id = "com.anthropic.claudefordesktop"
run = "move-node-to-workspace 4"
